# typos.toml - Configuration file for typos spellchecker

[default]
# Support multiple languages
locales = ["en", "es", "zh", "hi", "np"]

[default.extend-words]
ratatui = "ratatui"

# Optional: exclude specific files
# [files]
# exclude = ["*.md", "CHANGELOG.md"]
